# Generated by Django 5.0.6 on 2025-06-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AC', 'AC'), ('TV', 'TV'), ('Refrigerator', 'Refrigerator'), ('Mobile', 'Mobile'), ('Laptop', 'Laptop'), ('Microwave', 'Microwave'), ('Accessories', 'Accessories')], max_length=25)),
                ('image', models.ImageField(upload_to='assests/images')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('rating', models.SmallIntegerField()),
                ('price', models.FloatField()),
                ('expected_delivery', models.DateTimeField()),
            ],
        ),
    ]
